### PR TITLE
added bert demo

### PR DESCRIPTION
**Pull request by mohame54**
added Bert demo in examples and demos folder

### CODE REVIEW

**Comment by mohame54** [comment]
@juliagsy I am ready for the review

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey Mohamed! Thanks for the great work! Just one quick thing, would you mind to remove all cells output except the one printing/showing outputs. Also, could we also please show `compile` to all backend like here: https://unify.ai/demos/examples_and_demos/alexnet_demo.html
thanks a lot!

**Review by juliagsy — CHANGES_REQUESTED** [review]
Hey Mohamed! Thanks for the changes! Looks great and just 2 last things:
1. Not sure if I missed anything, but please add a title for the notebook
2. Again, not sure if I overlooked, but seems like the inference for ivy model in torch is missing?
Thanks!

**Comment by juliagsy** [comment]
Hey! Not sure if I missed anything, but I think your local changes are not yet sync in this PR? (for the title and torch section), thanks!

**Review by juliagsy — APPROVED** [review]
Thanks!

**Pull request merged**
