### PR TITLE
feat: Migrating demos to Sphinx

### PR DESCRIPTION
**Pull request by KareemMAX**
Feel free to see how it looks [here](https://kareemmax.github.io/demos/)

### CODE REVIEW

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
Looks good overall, but I liked the way the cells were rendered previously as opposed to now. The older one seems to be much more elegant where we don't the execution number on the left and the cell has enough padding to all sides as opposed to the new one. I've attached both images here, also the dark theme looks great except for the spacing thing I mentioned before. 
Let's see what @guillesanbri thinks, thanks @KareemMAX 😄
Screenshot 2023-08-29 at 12 14 03 PM
Screenshot 2023-08-29 at 12 15 14 PM

**Review by guillesanbri — CHANGES_REQUESTED** [review]
Yeah I agree with Ved, I think the previous paddings look better, can we modify this to some extent? it looks a bit too squeezed right now imo (e.g.)
image


Also, something which is definitely more important is that mobile rendering is significantly worse 
image
image

Lastly (very minor), links seem to break so we'll need to update them in all notebooks before merging 
image

**Comment by KareemMAX** [comment]
Hey @guillesanbri,
I guess the links are actually broken from the start, in `02_unify_code.ipynb` this is the last cell.

```md
Next, we'll be learning how to make our unified Ivy code [run much more efficiently]()! ⚡
```

I'll make changes to add the appropriate links, please review them as I might miss something.

**Comment by KareemMAX** [comment]
Hey @guillesanbri @vedpatwardhan, I've addressed your comments. Please let me know what do you think

**Review by vedpatwardhan — APPROVED** [review]
lgtm, let's see what @guillesanbri thinks.
Also, we'll be integrating this into our main documentation after this right? I mean moving this to `unify.ai/ivy/docs/examples`? Thanks @KareemMAX 😄

**Review by guillesanbri — APPROVED** [review]
Looks good to me as well, definitely more integrated with the docs page :smile: I think we can merge this. 

If we change the URLs me should ensure that the previous links redirect to the new ones tho, we have sent quite a lot of links to the older demos so definitely worth looking into it :+1:

**Pull request merged**
