### PR TITLE
Addition of Jupyter Notebook for Credit Card Fraud Detection Using Ivy Framework 


### LINKED ISSUE #90: Credit Card Fraud Detection Demo(Intermediate)
**Objective:** Develop a machine learning model with ivy to detect fraudulent transactions in credit card data. This project aims to address the critical issue of financial fraud, leveraging advanced analytics to identify suspicious activities.

**Task Details:**

- **Dataset:** The project will utilize the Credit Card Fraud Detection dataset available on Kaggle, accessible here: [Credit Card Fraud Detection Dataset](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud/data). This dataset contains transactions made by credit cards in September 2013 by European cardholders. Transactions are labeled as fraudulent or genuine, providing a comprehensive basis for developing a detection model.

- **Expected Output:** Contributors are expected to submit a Jupyter notebook that comprehensively documents the fraud detection model's development process. This includes data exploration, preprocessing, feature engineering, model training, and evaluation stages. The submission should also include the trained model files.

- **Submission Directory:** Your completed Jupyter notebook and model files should be placed in the `Contributor_demos/Credit Card Fraud Detection` subdirectory within the `unifyai/demos` repository.

**How to Contribute:**

1. Fork the `unifyai/demos` repository to your GitHub account.
2. Clone the forked repository to your local machine.
3. Create a new branch specifically for your work on the Credit Card Fraud Detection demo.
4. Develop your model, ensuring to document each step in the Jupyter notebook, from data analysis to the application of machine learning algorithms for fraud detection.
5. Save your notebook and model files in the `Contributor_demos/Credit Card Fraud Detection` directory.
6. Push your branch to your forked repository once your work is complete.
7. Submit a Pull Request (PR) to the `unifyai/demos` repository, making sure your PR title clearly indicates the project, such as "Credit Card Fraud Detection Demo Submission".

**Contribution Guidelines:**

- Make sure your code is well-documented to facilitate understanding and replication by others.
- Provide a summary of your methodology, significant findings, and any challenges you faced in the PR description, offering insights into your development process.

**Review and Feedback:**

Submissions will be reviewed on a rolling basis. Feedback or requests for modifications will be communicated through the PR discussion. Your contribution will be merged once it meets the project's standards and objectives, contributing significantly to the fight against financial fraud.

This project offers a meaningful opportunity to apply machine learning to a real-world problem with significant societal impact. We eagerly anticipate your innovative solutions and contributions to enhancing the security of financial transactions.

### PR DESCRIPTION
**Pull request by muzakkirhussain011**
### Changes Proposed in this Pull Request:
- **New Jupyter Notebook**: Added a Jupyter notebook that showcases the implementation of credit card fraud detection using the Ivy framework.
- **Ivy Framework Utilization**: The notebook demonstrates how to leverage the Ivy framework for building machine learning models tailored for fraud detection.
- **Data Analysis and Preprocessing**: Includes data analysis, preprocessing steps, and feature engineering to prepare the dataset for model training.
- **Model Training and Evaluation**: Details the process of training fraud detection models using the Ivy framework and evaluates their performance.
- **Results Visualization**: Provides visualizations of the results, including ROC curves and precision-recall curves, to better understand model performance.

### Impact of Change:
- This notebook will serve as a valuable resource for developers and data scientists looking to implement fraud detection systems using the Ivy framework.
- It contributes to the community by providing a practical example of applying machine learning to financial security.

### How to Test:
- Instructions are included within the notebook to set up the necessary environment and dependencies.
- Users can run the notebook cells sequentially to replicate the fraud detection process and verify the results.

### Additional Notes:
- The dataset used in this notebook is sourced from Kaggle.

Closes #90

### CODE REVIEW

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I have just pushed a commit that adds a Jupyter notebook for sarcasm detection using an LSTM model. This notebook also includes a demonstration of transpiling the TensorFlow model to PyTorch using Ivy, which significantly reduces training time while maintaining model performance.

I would greatly appreciate your review and feedback on this PR. Your insights will be invaluable to ensure the quality and effectiveness of the implementation.

Thank you for your time and consideration.

Best regards

**Review by vedpatwardhan — CHANGES_REQUESTED** [review]
Hey @muzakkirhussain011, actually the task requires using `ivy` as a framework to implement the model rather than transpiling a model in a different framework, could you please update the notebook accordingly? Thanks for creating the PR 😄

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,
Thank you for your review. I’ve attempted to implement the model using Ivy, but due to its current developmental stage, it lacks several methods and functions necessary for our model. This has led me to transpile the model from TensorFlow to PyTorch, which has shown better performance for our needs. I’m committed to updating the implementation as Ivy advances and includes the required features. For now, I believe the transpiled PyTorch model is the most viable solution. I appreciate your understanding and look forward to your feedback.

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,
Hey,

I appreciate the suggestion to use the existing LSTM layer and `ivy.lstm` function. However, there are several features and functionalities currently not available in Ivy that are crucial for building a robust sarcasm detection model. For instance, we lack `TensorDataset`, `DataLoader`, and a `zero_grad` function for optimizers. Moreover, the optimizer doesn't accept `model.parameters()` as an argument, and the loss function class doesn't have a `backward` method for the backward pass.

Most importantly, for a task like sarcasm detection, we need a comprehensive architecture that includes not just an LSTM but also embedding layers with full parameter support, bidirectional LSTM, and dense layers (linear layers). Without these, it's challenging to create an effective model.

It would be beneficial for the framework to consider incorporating these key features. Their addition promises to advance Ivy's deep learning capabilities and support more complex model development.

**Comment by vedpatwardhan** [comment]
> Hi @vedpatwardhan ,
> 
> I appreciate the suggestion to use the existing LSTM layer and `ivy.lstm` function. However, there are several features and functionalities currently not available in Ivy that are crucial for building a robust sarcasm detection model. For instance, we lack `TensorDataset`, `DataLoader`, and a `zero_grad` function for optimizers. Moreover, the optimizer doesn't accept `model.parameters()` as an argument, and the loss function class doesn't have a `backward` method for the backward pass.
> 
> Most importantly, for a task like sarcasm detection, we need a comprehensive architecture that includes not just an LSTM but also embedding layers with full parameter support, bidirectional LSTM, and dense layers (linear layers). Without these, it's challenging to create an effective model.
> 
> It would be beneficial for the framework to consider incorporating these key features. Their addition promises to advance Ivy's deep learning capabilities and support more complex model development.

Hey @muzakkirhussain011, actually the `Dataset`, `DataLoader` classes, etc. aren't present in the `ivy` repo (they are present on the `builder` repo), but that could actually be implemented functionally using `ivy`. As for the optimizer, given that `ivy`'s design has been made closer to `jax`, the optimizer doesn't really operate in the stateful manner and you can just pass `model.v` to the optimizer when calling `optimizer.step`. For both the dataset and optimizer issues, you can refer the example under the "I'm using Ivy" dropdown of [this](https://github.com/unifyai/ivy?tab=readme-ov-file#using-ivy) section. Ofc feel free to make necessary changes to how you'd generate batches, etc. Happy to answer any further questions, thanks 😄

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,

I would like to request your expertise in reviewing a recent commit that includes a Jupyter notebook for our credit card fraud detection project. This notebook is integral to our initiative, as it employs the Ivy framework throughout all stages—training, prediction, and evaluation. Your insights would be greatly appreciated to ensure the thoroughness and accuracy of our methodologies.

Thank you for your assistance.
Best regards

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I have just pushed a commit that adds a Jupyter notebook for our credit card fraud detection project. This notebook is integral to our initiative, as it employs the Ivy framework throughout all stages—training, prediction, and evaluation. Your insights would be greatly appreciated to ensure the thoroughness and accuracy of our methodologies.

Thank you for your time and consideration.

Best regards

**Comment by NripeshN** [comment]
> Hi @NripeshN ,
> 
> I have just pushed a commit that adds a Jupyter Notebook for our credit card fraud detection project. This notebook is integral to our initiative, as it employs the Ivy framework throughout all stages—training, prediction, and evaluation. Your insights would be greatly appreciated to ensure the thoroughness and accuracy of our methodologies.
> 
> Thank you for your time and consideration.
> 
> Best regards

Hey @muzakkirhussain011 
Could you please create 2 different PRs for the 2 problem statement? 
Note: The `Credit Card Fraud Detection` would not be considered if someone else creates a PR soon as in the form you had selected `Sarcasm Detection` and `credit card fraud detection` is only available for our `Rising Contributors`.

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

Thank you for your guidance. I understand the need for separate PRs for different problem statements. I have removed the sarcasm detection notebook due to persistent errors and plan to address it in a future PR. For now, I am focusing solely on the credit card fraud detection notebook. All stages of training, predicting, and evaluation are implemented within the Ivy framework. This PR will be exclusively for the credit card fraud detection notebook.

I appreciate the heads-up regarding the availability of the credit card fraud detection for Rising Contributors. I’ll ensure to submit my PR promptly to avoid any overlap with other contributors.

Best regards

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,

I wanted to highlight that the current PR is dedicated exclusively to credit card fraud detection. The notebook on sarcasm detection has been removed due to persistent errors.

Looking forward to your review.

Best Regards

**Comment by vedpatwardhan** [comment]
@NripeshN could you please review the PR? Thanks @muzakkirhussain011 😄

**Comment by NripeshN** [comment]
Could you please tidy the notebook a little bit with Markdowns explaining what you are doing etc. You can use [this](https://www.kaggle.com/code/joparga3/in-depth-skewed-data-classif-93-recall-acc-now) notebook for reference.
Thanks!

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

Thank you for your feedback. I've updated the Jupyter notebook to enhance its clarity and tidiness. Now, it includes detailed markdown annotations explaining each step of the analysis and the corresponding code blocks. I've made sure to follow the structure and documentation style of the reference notebook you provided.

Please have a look and let me know if there are any further improvements you'd like to see.

Best regards

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I’m just checking in on the updates made to the Jupyter notebook. I’ve incorporated detailed markdown annotations and restructured the code blocks for enhanced clarity, as per your suggestions.

Could you please review the changes at your earliest convenience? If all is in order, I would appreciate if we could move forward with merging the PR.

Looking forward to your feedback.

Best regards

**Comment by NripeshN** [comment]
> Hi @NripeshN ,
> 
> I’m just checking in on the updates made to the Jupyter notebook. I’ve incorporated detailed markdown annotations and restructured the code blocks for enhanced clarity, as per your suggestions.
> 
> Could you please review the changes at your earliest convenience? If all is in order, I would appreciate if we could move forward with merging the PR.
> 
> Looking forward to your feedback.
> 
> Best regards

I have asked for a few changes. Once done the PR looks good to be merged

**Comment by NripeshN** [comment]
> Hi @NripeshN ,
> 
> Thank you for your feedback on the PR. Could you please specify the changes you're referring to? This will help me address them accurately and ensure the PR is ready for merging.
> 
> Best regards

I left a review above. Just tagged you in it again.

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I couldn't find the review you mentioned. Could you please point me to it or resend? Also, a quicker response would help me act on it sooner.

Thanks

**Comment by muzakkirhussain011** [comment]
> Hey @muzakkirhussain011, actually the task requires using `ivy` as a framework to implement the model rather than transpiling a model in a different framework, could you please update the notebook accordingly? Thanks for creating the PR 😄

Hey @vedpatwardhan 

I've updated the notebook to use Ivy exclusively for all stages—training, predicting, and testing—without any transpiling. Could you please review and approve the requested changes?

Thanks!

**Comment by NripeshN** [comment]
> Hi @NripeshN ,
> 
> I couldn't find the review you mentioned. Could you please point me to it or resend? Also, a quicker response would help me act on it sooner.
> 
> Thanks

There are a few pending reviews above. Please address them.
image

**Comment by muzakkirhussain011** [comment]
Thank you for the reminder. I have addressed the pending reviews for the deletion of `contributor_demos/Sarcasm Detection/requirements.txt` as suggested. If there are any further changes needed, please let me know.

**Comment by NripeshN** [comment]
> Hi @NripeshN Thank you for the reminder. I have addressed the pending reviews for the deletion of `contributor_demos/Sarcasm Detection/requirements.txt` as suggested. If there are any further changes needed, please let me know.

Hey @muzakkirhussain011 
There are 2 more pending changes I requested
image
image

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I've made the requested changes. Could you please review them at your earliest convenience? If there's anything else that needs attention, just let me know.

Thank you!

**Comment by NripeshN** [comment]
> Hi @NripeshN ,
> 
> 
> 
> I've made the requested changes. Could you please review them at your earliest convenience? If there's anything else that needs attention, just let me know.
> 
> 
> 
> Thank you!
> 
> 

Hey @muzakkirhussain011,
Looks like not all the packages are installed to run the notebook using requirements.txt. Can you please add all the requirements?

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN 

The requirements.txt file includes all the necessary libraries that aren’t available by default in Colab. I’ve executed the code successfully in Colab without any issues.

Best regards,

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I appreciate your review and the heads-up regarding the requirements.txt. I have gone through the file once more and added all the missing libraries that are essential for running the notebook. The updated requirements.txt is now part of the pull request. Please let me know if everything works fine or if there’s anything else needed.

Thank you for your patience and assistance.

Best

**Comment by NripeshN** [comment]
> Hi @NripeshN ,
> 
> I appreciate your review and the heads-up regarding the requirements.txt. I have gone through the file once more and added all the missing libraries that are essential for running the notebook. The updated requirements.txt is now part of the pull request. Please let me know if everything works fine or if there’s anything else needed.
> 
> Thank you for your patience and assistance.
> 
> Best

Hi @muzakkirhussain011 
Could you please add all the dependencies that are needed to run the notebook in `requirement.txt`.

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I've updated the `requirements.txt` file with all the necessary dependencies for the notebook. Please check and confirm if everything is running smoothly on your end. Your prompt response would be appreciated!

Thank you.

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I've updated the requirements.txt file with all the necessary dependencies for the notebook. Please check and confirm if everything is running smoothly on your end. Your prompt response would be appreciated!

Thank you.

**Comment by muzakkirhussain011** [comment]
> Hi @muzakkirhussain011 
> Could you please add all the dependencies that are needed to run the notebook in `requirement.txt`. Seems like some packages are missing in `requirement.txt`

Hi @NripeshN ,

I've updated the requirements.txt file with all the necessary dependencies for the notebook. Please check and confirm if everything is running smoothly on your end. Your prompt response would be appreciated!

Thank you.

**Comment by NripeshN** [comment]
> > Hi @muzakkirhussain011
> > Could you please add all the dependencies that are needed to run the notebook in `requirement.txt`. Seems like some packages are missing in `requirement.txt`
> 
> Hi @NripeshN ,
> 
> I've updated the requirements.txt file with all the necessary dependencies for the notebook. Please check and confirm if everything is running smoothly on your end. Your prompt response would be appreciated!
> 
> Thank you.

Hey @muzakkirhussain011 

I see you have used `pip freeze` to add all the requirements, but this approach adds a lot of requirements that come along the main packages anyway. Could you just add the main packages you used in the notebook?
Thanks!

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN 

I’ve updated the requirements file to include only the main packages used in the notebook. 

Thanks

**Comment by NripeshN** [comment]
> Hi @NripeshN
> 
> I’ve updated the requirements file to include only the main packages used in the notebook.
> 
> Thanks

Hey @muzakkirhussain011,
Is there a reason we are mentioning the pip package's version? Why are we just not downloading the latest version?

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

Updated the pip packages to install the latest versions automatically. Please let me know if you have any concerns or further questions.

**Comment by muzakkirhussain011** [comment]
Hi @NripeshN ,

I've made the necessary updates, and if everything checks out on your end, could you please merge the PR? Looking forward to your prompt response. 

Thank you!

**Review by NripeshN — APPROVED** [review]
LGTM!

**Pull request merged**
