### PR TITLE
fix: moves processing to gpu + general clean up

### PR DESCRIPTION
**Pull request by rishabgit**
Current live demo processes entirely on CPU and breaks due to low RAM on running resnet 50 piece
This PR uses GPU to avoid termination and removes all redundant prints which make it difficult to read through the demo

### CODE REVIEW

**Comment by guillesanbri** [comment]
might be worth adding a small statement on top asking them to switch to a gpu environment if using colab :+1:

**Comment by rishabgit** [comment]
> might be worth adding a small statement on top asking them to switch to a gpu environment if using colab 👍

@guillesanbri most (if not all?) demos assume users are on gpu i think (e.g. manually moves tensors to cuda) - would you like me to put that text in all demos? 😅

**Comment by rishabgit** [comment]
@guillesanbri added the gpu requirement line in relevant demos 😄

**Review by guillesanbri — APPROVED** [review]
lgtm :+1:

**Pull request merged**
