### PR TITLE
Add AI Debate App Demo

### PR DESCRIPTION
**Pull request by Sanjay8602**
Description
This pull request introduces a new Streamlit application, AI Debate App, to the existing repository of UnifyAI demos.
Debate-App is a web application that enables a back-and-forth conversation between two Language Models (LLMs) on a topic chosen by the user. Users can select any two models, input a query, and visualize the dialogue between the LLMs in real-time.

Changes
New Files:  Added all necessary files for the Debate app, including app.py, requirements.txt, and related assets.

Updated Documentation: Included detailed instructions in the README.md within the AI Debate App directory, outlining how to set up and run the application locally and how to access the hosted version.

Demo Video: Link of demo video is attached in the README file of this PR for better visualization

### CODE REVIEW

**Review by Sanjay8602 — COMMENTED** [review]
updated readme

**Comment by hello-fri-end** [comment]
Hey @Sanjay8602, could you please upload the code as well? The README looks good :)

**Review by Sanjay8602 — COMMENTED** [review]
added the file

**Comment by Sanjay8602** [comment]
> added the files

**Comment by hello-fri-end** [comment]
LGTM! Thanks for the contribution @Sanjay8602! 🥳

**Pull request merged**
