### PR TITLE
LlamaIndex RAGPlayground

### PR DESCRIPTION
**Pull request by abhi2596**

### CODE REVIEW

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @abhi2596 ! Thank you for making this contribution :muscle: :rocket: . I moved the demo video section to the top in the [template readme](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md) to  better catch the attention of the viewer. Could you please look at the changes and update the README?  You can take a look the [README of LLM-Wars project](https://github.com/unifyai/demos/blob/main/Unify/LLM-Wars/README.md?plain=1) for an example.  Happy to review again once you're done! :)

P.S could you please uncommit the __pycache__folder? Thanks!

**Comment by abhi2596** [comment]
changes done as requested

**Review by hello-fri-end — CHANGES_REQUESTED** [review]
Hey @abhi2596 , you need to pull the latest changes from the repo and add your demo video to the Videos folder as mentioned [here](https://github.com/unifyai/demos/blob/main/template/README_TEMPLATE.md?plain=1#L4-L10).

**Comment by abhi2596** [comment]
@hello-fri-end Can you check now?

**Comment by hello-fri-end** [comment]
LGTM! Thanks for the contribution! @abhi2596

**Pull request merged**
