### PR TITLE
docs: add functions output for quickstart

### PR DESCRIPTION
**Pull request by a0m0rajab**
This pr only adds the output of the file to the demo to show it to the user without the need to run the file manually. 

This PR is based on the request from this thread on Discord:
https://discord.com/channels/799879767196958751/1145060258729971834

### CODE REVIEW

**Comment by a0m0rajab** [comment]
@KareemMAX and @guillesanbri could you check this?

**Review by guillesanbri — CHANGES_REQUESTED** [review]
Hey, didn't get a notification before, best to request a review when doing a PR in the future :)

Looks good, just a couple of minor changes:

1) We can probably remove the output of cell [2]

2) Same in cell [4], we can remove the warning from the output

3) Same in [11]

4) The output of cell [12] should be rendered, I think @KareemMAX reported this a time ago, not sure if there is a workaround

5) Same with the warning in [28] and [33]

For me the easiest way to keep things organized is by manually removing the output of these cells editing the notebook as a text file if that makes sense, otherwise execution numbers can get messy

**Comment by a0m0rajab** [comment]
@guillesanbri the output in cell 12 is rendered though: 
image

The I did remove the warnings.

**Comment by guillesanbri** [comment]
Ah good to hear, doesn't show up in the github preview to me for some reason

**Review by guillesanbri — APPROVED** [review]

**Comment by a0m0rajab** [comment]
Thank you for that! by github preview do you mean codespace?

**Comment by guillesanbri** [comment]
> Thank you for that! by github preview do you mean codespace?

not really, in the github website directly i.e. https://github.com/a0m0rajab/unify.ai-demos/blob/main/quickstart.ipynb

**Pull request merged**
