### PR TITLE
Add LLM Wars demo

### PR DESCRIPTION
**Pull request by leebissessar5**
### Description
This pull request introduces a new Streamlit application, **LLM Wars**, to the existing repository of UnifyAI demos. LLM Wars is a competitive interaction platform where two Large Language Models (LLMs) challenge each other in a battle of wits by asking and evaluating prompts. A judge LLM determines the winner based on the responses. This addition aims to showcase the capabilities of LLMs in generating and understanding complex queries in a fun and engaging way.

### Changes
- **New Files**: Added all necessary files for the LLM Wars application under the `LLM Wars` directory, including `main.py`, `requirements.txt`, and related assets.
- **Updated Documentation**: Included detailed instructions in the `README.md` within the `LLM Wars` directory, outlining how to set up and run the application locally and how to access the hosted version.
- **Demo Video**: A link to a demo video of the application in action is provided in the README for better understanding and visualization.

### CODE REVIEW

**Comment by leebissessar5** [comment]
@hello-fri-end, could you please review this pull request when you have a chance? Thank you!

**Comment by hello-fri-end** [comment]
Hey @leebissessar5, the README looks good to me. Could you please upload all the code as well? Thanks!

**Comment by leebissessar5** [comment]
> Hey @leebissessar5, the README looks good to me. Could you please upload all the code as well? Thanks!

Done👍

**Comment by hello-fri-end** [comment]
LGTM! Thanks for the contribution @leebissessar5 ! 🥳

**Pull request merged**
