### PR TITLE
Addition of "Talk To Your Data" Streamlit App 

### PR DESCRIPTION
**Pull request by muzakkirhussain011**
#### 📌 Overview  
This PR introduces the **Talk To Your Data** application, a powerful interactive tool built using Streamlit. It allows users to explore their datasets effortlessly through natural language queries. The app leverages **LLMs** to generate insights and visualizations, providing a seamless way to perform data analysis without complex coding.  

#### 🔑 Key Features  
- **Interactive Data Exploration**: Users can analyze datasets by asking natural language questions.  
- **Dataset Upload Capability**: Easily upload datasets directly through the app interface.  
- **LLM-Powered Insights**: Responses and insights are powered by Unify AI models.  

#### 📂 Changes Introduced  
- Implemented a **Streamlit app** that processes user-uploaded datasets and answers queries with insights and visualizations.  
- Integrated **Unify AI models** to provide responses based on user queries.  
- Enhanced the UI for a smooth user experience, including dataset upload and visual output.  
- Added error handling to manage unsupported queries or incorrect data formats.  

#### 🧪 Testing & Validation  
- Verified the successful installation and launch of the app with:  
   ```bash
   pip install -r requirements.txt  
   streamlit run app.py  

[🚀 Demo](https://talk-to-your-data-unifyai.streamlit.app/)  

https://github.com/user-attachments/assets/1d4134cc-3855-433e-a789-d7764f25a7f8

<video width="640" height="480" autoplay>
  <source src="../../../../_static/Talk_To_Your_Data.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>

### CODE REVIEW

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan , 👋

This PR introduces the **Talk To Your Data** Streamlit app, enabling interactive data exploration through natural language queries powered by Unify AI. I've ensured that the core features are functional and the app runs smoothly.  

Looking forward to your feedback and suggestions! Let me know if any changes or improvements are required.  

Thank you for your time and review!

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan 

I hope this message finds you well. I wanted to follow up on the pull request I submitted earlier this week concerning the Talk To Your Data Streamlit app. Whenever you have a moment, I would greatly appreciate any feedback or suggestions you might have.

Thank you for your time and consideration.

Best regards

**Comment by vedpatwardhan** [comment]
Hey @muzakkirhussain011, we're a bit heads down right now, we'll get back to you on the PR soon 😄

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan , 
Thanks for the update! No worries, just wanted to check in. Looking forward to your feedback when you get the chance. Thanks!

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,

I hope you're well. Just a friendly follow-up on the pull request I submitted 4 days ago. I've added a demo video of the Streamlit app and a link to the deployed app in the PR description for your reference. I appreciate your time and look forward to your feedback when it's convenient. 
Thank you

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan 

I hope you're well. Just a friendly follow-up on the pull request I submitted 15 days ago. I've added a demo video of the Streamlit app and a link to the deployed app in the PR description for your reference. Here is the link to the deployed app for your convenience: [Streamlit App](https://talk-to-your-data-unifyai.streamlit.app/). I appreciate your time and look forward to your feedback when it's convenient. 
Thank you.

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,

I hope you're doing well. I wanted to follow up regarding the pull request I submitted about 20 days ago. To provide a clearer picture, I’ve included the PR link, a Streamlit-deployed app link, and a video demo showcasing the functionality.

- **GitHub PR**: [PR Link](https://github.com/unifyai/demos/pull/15)
- **Streamlit App**: [Streamlit App](https://talk-to-your-data-unifyai.streamlit.app/)

If there’s anything specific I can improve or clarify, please let me know. I’m eager to contribute and appreciate any feedback you might have.

Thanks for your time and consideration!

Best regards

**Comment by muzakkirhussain011** [comment]
Hi @guillesanbri ,

I hope this message finds you well.

I wanted to follow up on the pull request I submitted 21 days ago. Could you please take a look and provide your feedback? Your input would be greatly appreciated.

Thank you for your time and consideration.

Best regards,

**Comment by muzakkirhussain011** [comment]
Hi @guillesanbri ,

I hope this message finds you well.

I wanted to follow up on the pull request I submitted 21 days ago. Could you please take a look and provide your feedback? Your input would be greatly appreciated.

Thank you for your time and consideration.

Best regards

[Streamlit app](https://talk-to-your-data-unifyai.streamlit.app/)  

https://github.com/user-attachments/assets/1d4134cc-3855-433e-a789-d7764f25a7f8

<video width="640" height="480" autoplay>
  <source src="../../../../_static/Talk_To_Your_Data.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan ,

I hope all is going well with the current priorities. I wanted to check in on the PR I submitted, as it’s been a bit of time since I last followed up. If there’s anything further you need from my side or if there are additional requirements for this PR, I’d be glad to assist.

Thank you for your time, and I appreciate any update you’re able to provide!

Best

**Comment by muzakkirhussain011** [comment]
Hi @hello-fri-end 

I hope this message finds you well.

I wanted to follow up on the pull request I submitted 24 days ago. Could you please take a look and provide your feedback? Your input would be greatly appreciated.

Thank you for your time and consideration.

Best regards


[Streamlit app](https://talk-to-your-data-unifyai.streamlit.app/)  

https://github.com/user-attachments/assets/1d4134cc-3855-433e-a789-d7764f25a7f8

<video width="640" height="480" autoplay>
  <source src="../../../../_static/Talk_To_Your_Data.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan,

Thank you for getting back to me. I understand the need to revert the changes to the ChatBot Arena demo.

To clarify, I actually copied the entire code from the original repository and replaced the modified code to ensure that no changes were made to the ChatBot Arena demo. Hence, the code should be identical to the original.

I tried to revert the commits as you suggested, but I faced some difficulties in doing so. Could you please let me know if there's anything else specific I need to do, or if there are additional steps required?

Thank you for your guidance and patience!

Best regards

**Comment by muzakkirhussain011** [comment]
Hi @vedpatwardhan,

Thank you for your previous response.

Given that the code for the ChatBot Arena demo has been replaced with the original code and remains unchanged, I would like to request if you could proceed with merging the PR. I faced difficulties in reverting the commits, and since the current state of the code is identical to the original, it should be ready for merging.

If there's anything else specific I need to do, or if there are additional steps required, please let me know.

Thank you once again for your guidance and patience!

Best regards

**Pull request closed without merging**
